apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-11-23T22:53:08Z"
  generation: 1
  labels:
    app: app-one
  name: app-one
  namespace: default
  resourceVersion: "3066"
  uid: 6d6c8d2f-b4d5-47f6-a974-1d1488633ffb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app-one
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-one
    spec:
      serviceAccountName: dk98-ksa
      containers:
      - image: gcr.io/ds-561/appone:1.0.0
        imagePullPolicy: IfNotPresent
        name: appone
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-23T22:53:15Z"
    lastUpdateTime: "2023-11-23T22:53:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-23T22:53:08Z"
    lastUpdateTime: "2023-11-23T22:53:15Z"
    message: ReplicaSet "app-one-9bb97849d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
